SELECT TOP (1000) [SaleID]
      ,[EmployeeKey]
      ,[ProductKey]
      ,[ResellerKey]
      ,[OrderDate]
      ,[OrderQuantity]
      ,[UnitPrice]
      ,[PromotionKey]
      ,[CurrencyKey]
      ,[SalesTerritoryKey]
      ,[TotalAmount]
  FROM [MyDataWarehouse].[dbo].[FactSales]
